version: "3.7"
services:
  db:
    container_name: "postgres_data_product"
    image: "postgres"
    # build: .
    volumes:
      - ./pg-init-scripts:/docker-entrypoint-initdb.d
      - ./postgres-data:/var/lib/postgresql/data
    environment:
      - POSTGRES_MULTIPLE_DATABASES= oltp,olap
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5432:5432'
      